#!/bin/sh

rm -f src/Makevars src/libprofit/include/profit/config.h
rm -f src/libprofit/include/profit/cl/*-float.h
rm -f src/libprofit/include/profit/cl/*-double.h
rm -f src/*.o
rm -f src/libprofit/src/*.o
