// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// profitSumPix
double profitSumPix(double xcen, double ycen, NumericVector xlim, NumericVector ylim, double re, double nser, double angrad, double axrat, double box, double bn, int Nsamp, int recur, int depth, double acc);
RcppExport SEXP ProFit_profitSumPix(SEXP xcenSEXP, SEXP ycenSEXP, SEXP xlimSEXP, SEXP ylimSEXP, SEXP reSEXP, SEXP nserSEXP, SEXP angradSEXP, SEXP axratSEXP, SEXP boxSEXP, SEXP bnSEXP, SEXP NsampSEXP, SEXP recurSEXP, SEXP depthSEXP, SEXP accSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type xcen(xcenSEXP);
    Rcpp::traits::input_parameter< double >::type ycen(ycenSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xlim(xlimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ylim(ylimSEXP);
    Rcpp::traits::input_parameter< double >::type re(reSEXP);
    Rcpp::traits::input_parameter< double >::type nser(nserSEXP);
    Rcpp::traits::input_parameter< double >::type angrad(angradSEXP);
    Rcpp::traits::input_parameter< double >::type axrat(axratSEXP);
    Rcpp::traits::input_parameter< double >::type box(boxSEXP);
    Rcpp::traits::input_parameter< double >::type bn(bnSEXP);
    Rcpp::traits::input_parameter< int >::type Nsamp(NsampSEXP);
    Rcpp::traits::input_parameter< int >::type recur(recurSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< double >::type acc(accSEXP);
    __result = Rcpp::wrap(profitSumPix(xcen, ycen, xlim, ylim, re, nser, angrad, axrat, box, bn, Nsamp, recur, depth, acc));
    return __result;
END_RCPP
}
// profitMakeSersic
NumericMatrix profitMakeSersic(double xcen, double ycen, double mag, double re, double nser, double ang, double axrat, double box, double magzero, int rough, NumericVector xlim, NumericVector ylim, IntegerVector dim);
RcppExport SEXP ProFit_profitMakeSersic(SEXP xcenSEXP, SEXP ycenSEXP, SEXP magSEXP, SEXP reSEXP, SEXP nserSEXP, SEXP angSEXP, SEXP axratSEXP, SEXP boxSEXP, SEXP magzeroSEXP, SEXP roughSEXP, SEXP xlimSEXP, SEXP ylimSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type xcen(xcenSEXP);
    Rcpp::traits::input_parameter< double >::type ycen(ycenSEXP);
    Rcpp::traits::input_parameter< double >::type mag(magSEXP);
    Rcpp::traits::input_parameter< double >::type re(reSEXP);
    Rcpp::traits::input_parameter< double >::type nser(nserSEXP);
    Rcpp::traits::input_parameter< double >::type ang(angSEXP);
    Rcpp::traits::input_parameter< double >::type axrat(axratSEXP);
    Rcpp::traits::input_parameter< double >::type box(boxSEXP);
    Rcpp::traits::input_parameter< double >::type magzero(magzeroSEXP);
    Rcpp::traits::input_parameter< int >::type rough(roughSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xlim(xlimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ylim(ylimSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    __result = Rcpp::wrap(profitMakeSersic(xcen, ycen, mag, re, nser, ang, axrat, box, magzero, rough, xlim, ylim, dim));
    return __result;
END_RCPP
}
// profitBruteConv
NumericMatrix profitBruteConv(NumericMatrix image, NumericMatrix psf);
RcppExport SEXP ProFit_profitBruteConv(SEXP imageSEXP, SEXP psfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type image(imageSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type psf(psfSEXP);
    __result = Rcpp::wrap(profitBruteConv(image, psf));
    return __result;
END_RCPP
}
