// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// profitDownsample
NumericMatrix profitDownsample(const NumericMatrix& IMG, const int DOWNSAMPLEFAC);
RcppExport SEXP ProFit_profitDownsample(SEXP IMGSEXP, SEXP DOWNSAMPLEFACSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type IMG(IMGSEXP);
    Rcpp::traits::input_parameter< const int >::type DOWNSAMPLEFAC(DOWNSAMPLEFACSEXP);
    rcpp_result_gen = Rcpp::wrap(profitDownsample(IMG, DOWNSAMPLEFAC));
    return rcpp_result_gen;
END_RCPP
}
// profitUpsample
NumericMatrix profitUpsample(const NumericMatrix& IMG, const int UPSAMPLEFAC);
RcppExport SEXP ProFit_profitUpsample(SEXP IMGSEXP, SEXP UPSAMPLEFACSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type IMG(IMGSEXP);
    Rcpp::traits::input_parameter< const int >::type UPSAMPLEFAC(UPSAMPLEFACSEXP);
    rcpp_result_gen = Rcpp::wrap(profitUpsample(IMG, UPSAMPLEFAC));
    return rcpp_result_gen;
END_RCPP
}
