profitLikeModel=function(parm, Data, makeplots=FALSE, 
  whichcomponents=list(sersic="all",moffat="all",ferrer="all",pointsource="all"), rough=FALSE,
  cmap = rev(colorRampPalette(brewer.pal(9,'RdYlBu'))(100)), errcmap=cmap, plotchisq=FALSE) {
  if(class(Data)!='profit.data'){stop("The Data must be of class profit.data, as generated by the profitSetupData function!")}

  finesample = 1L
  if(length(Data$finesample)>0) finesample = Data$finesample
  profitCheckFinesample(finesample)
  
  remakeout=profitRemakeModellist(parm=parm, Data=Data)
  modellistnew=remakeout$modellist
  parm=remakeout$parm
  
  # Calculate priors with the new versus old modellist
  if(length(Data$priors)>0){
    priorsum=Data$priors(modellistnew,Data$modellist)
  }else{
    priorsum=0
  }
  
  if(Data$fitpsf) {
    psf = profitMakePointSource(modellist=modellistnew$psf, finesample = finesample) 
  } else {
    psf = Data$psf
  }
  
  if(Data$usecalcregion){
    model = profitMakeModel(modellist=modellistnew, magzero = Data$magzero, psf=Data$psf, dim=Data$imagedim, 
      whichcomponents = whichcomponents, rough=rough, calcregion=Data$calcregion, docalcregion=Data$usecalcregion,
      magmu=Data$magmu,finesample=finesample, convopt=Data$convopt, openclenv=Data$openclenv)
  }else{
    model = profitMakeModel(modellist=modellistnew, magzero = Data$magzero, psf=Data$psf, dim=Data$imagedim, 
      whichcomponents = whichcomponents, rough=rough, magmu=Data$magmu, finesample=finesample, convopt=Data$convopt, openclenv=Data$openclenv)
  }
  
  cutsig=Data$sigma
  cutim=Data$image
  cutmod=model$z
  if(!is.null(Data$region)) {
    cutim=cutim[Data$region]
    cutmod=cutmod[Data$region]
    cutsig=cutsig[Data$region] 
  }

  #Force like.func to be lower case:
  Data$like.func=profitParseLikefunc(Data$like.func)
  
  #Various allowed likelihoods:
  isnorm = Data$like.func == "norm"
  ischisq = Data$like.func == "chisq"
  ist = Data$like.func == "t"
  if(isnorm || ischisq || ist) {
    cutsig=(cutim-cutmod)/cutsig
  }
  if(isnorm){
    LL=sum(dnorm(cutsig, log=TRUE))
  } else if(ischisq) {
    ndata = length(cutim)
    LL=dchisq(sum(cutsig^2), ndata, log=TRUE)
  } else if(ist) {
    vardata = var(cutsig,na.rm = TRUE)
    dof=2*vardata/(vardata-1)
    dof=interval(dof,0,Inf)
    LL=sum(dt(cutsig,dof,log=TRUE))
  } else if(Data$like.func=="pois") {
    scale=max(abs(Data$image)/abs(Data$sigma)^2)
    if(scale<0.1 | scale>10){
      cutmod=cutmod*scale
      cutim=cutim*scale
    }
    LL=-sum(cutmod-cutim*log(cutmod))
  } else {
    stop(paste0("Error: unknown likelihood function: '",Data$like.func,"'"))
  }
  
  if(makeplots){
    skylevel = 0
    if(!is.null(modellistnew$sky) && !is.null(modellistnew$sky$bg) && is.numeric(modellistnew$sky$bg)) skylevel = modellistnew$sky$bg
    profitMakePlots(Data$image-skylevel,model$z-skylevel,Data$region, Data$sigma, cmap=cmap, errcmap=errcmap,plotchisq=plotchisq)
  }
  
  LP=as.numeric(LL+priorsum)
  if(Data$verbose){print(c(parm,LP),digits = 5)}
  if(Data$algo.func=='') return(list(model=model,psf=psf))
  if(Data$algo.func=='optim' | Data$algo.func=='CMA'){out=LP}
  if(Data$algo.func=='LA' | Data$algo.func=='LD'){
    if(ist) Monitor=c(LL=LL,LP=LP,dof=dof) else Monitor=c(LL=LL,LP=LP)
    out=list(LP=LP,Dev=-2*LL,Monitor=Monitor,yhat=1,parm=parm)
  }
  return(out)
}