profitMakePSF=function(xcen,ycen,mag=15,image,psf,magzero=0){
  scale=10^(-0.4*(mag-magzero))
  limx=c(1,dim(image)[1])
  limy=c(1,dim(image)[2])
  remapgrid=expand.grid(seq(-dim(psf)[1]/2,dim(psf)[1]/2,len=dim(psf)[1]),seq(-dim(psf)[2]/2,dim(psf)[2]/2,len=dim(psf)[2]))
  offx=(xcen+(dim(psf)[1]%%2)/2)%%1
  offy=(ycen+(dim(psf)[2]%%2)/2)%%1
  pixlocx=xcen-offx-floor(dim(psf)[1]/2)+1
  pixlocy=ycen-offy-floor(dim(psf)[2]/2)+1
  remapgrid[,1]=remapgrid[,1]-offx
  remapgrid[,2]=remapgrid[,2]-offy
  remappsf=matrix(profitInterp2d(remapgrid[,1],remapgrid[,2],psf)[,3],dim(psf)[1],dim(psf)[2])
  output=profitAddMats(image,remappsf*scale,c(pixlocx,pixlocy))
  return=output
}