# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

profitSumPix <- function(xcen, ycen, xlim, ylim, re, nser, angrad, axrat, box, bn, Nsamp, recur = 0L, depth = 5L, acc = 0.1) {
    .Call('ProFit_profitSumPix', PACKAGE = 'ProFit', xcen, ycen, xlim, ylim, re, nser, angrad, axrat, box, bn, Nsamp, recur, depth, acc)
}

profitMakeSersic <- function(xcen = 0, ycen = 0, mag = 15, re = 1, nser = 1, ang = 0, axrat = 1, box = 0, magzero = 0, rough = 0L, xlim = as.numeric( c(-100,100)), ylim = as.numeric( c(-100,100)), dim = as.integer( c(200,200))) {
    .Call('ProFit_profitMakeSersic', PACKAGE = 'ProFit', xcen, ycen, mag, re, nser, ang, axrat, box, magzero, rough, xlim, ylim, dim)
}

profitBruteConv <- function(image, psf) {
    .Call('ProFit_profitBruteConv', PACKAGE = 'ProFit', image, psf)
}

