# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

profitDownsample <- function(IMG, DOWNSAMPLEFAC) {
    .Call('ProFit_profitDownsample', PACKAGE = 'ProFit', IMG, DOWNSAMPLEFAC)
}

profitUpsample <- function(IMG, UPSAMPLEFAC) {
    .Call('ProFit_profitUpsample', PACKAGE = 'ProFit', IMG, UPSAMPLEFAC)
}

