# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

profitMakeSersic <- function(CALCREGION, XCEN = 0, YCEN = 0, MAG = 15, RE = 1, NSER = 1, ANG = 0, AXRAT = 1, BOX = 0, MAGZERO = 0, ROUGH = FALSE, XLIM = as.numeric( c(-100,100)), YLIM = as.numeric( c(-100,100)), DIM = as.integer( c(200,200)), UPSCALE = 8L, MAXDEPTH = 2L, RESWITCH = 2, ACC = 0.1, DOCALCREGION = FALSE, REMAX = 10) {
    .Call('ProFit_profitMakeSersic', PACKAGE = 'ProFit', CALCREGION, XCEN, YCEN, MAG, RE, NSER, ANG, AXRAT, BOX, MAGZERO, ROUGH, XLIM, YLIM, DIM, UPSCALE, MAXDEPTH, RESWITCH, ACC, DOCALCREGION, REMAX)
}

profitBruteConv <- function(image, psf, CALCREGION, DOCALCREGION = FALSE) {
    .Call('ProFit_profitBruteConv', PACKAGE = 'ProFit', image, psf, CALCREGION, DOCALCREGION)
}

